### ISSUE TITLE
Strange Set methods

### ISSUE THREAD

**Issue by Yustos** [darthfabar/DistributedCachePollyDecorator#2]
https://github.com/darthfabar/DistributedCachePollyDecorator/blob/4798bf05b497f2cf702faa51550e7d724292772f/Source/DistributedCachePollyDecorator/PolicyDistributedCacheDecorator.cs#L92

Why you remove item in set methods?

**Comment by darthfabar** [comment]
Hi,
Thanks for you issue. Your totally right and this is a copy and paste bug

**Comment by Yustos** [comment]
Thanks for great decorator, scrutor and polly example! And for nice package.

**Comment by darthfabar** [comment]
Thanks for your feedback, I'm glade you like it :)
